# Generated by Django 4.2.21 on 2025-05-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='The original long URL to be shortened.', max_length=2048)),
                ('short_code', models.CharField(blank=True, help_text='Auto-generated short code.', max_length=10, unique=True)),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of times the short URL was accessed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration date for the short URL.', null=True)),
            ],
        ),
    ]
