# Generated by Django 4.2.21 on 2025-05-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
    ]
