# Generated by Django 4.2.19 on 2025-03-04 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(verbose_name='Original URL')),
                ('short_code', models.CharField(max_length=10, unique=True, verbose_name='Shortened Code')),
                ('custom_alias', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Custom Alias')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='URL',
        ),
    ]
