# Generated by Django 4.2.19 on 2025-03-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_shortenedurl_delete_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedurl',
            name='user',
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='custom_alias',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='original_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
