# Generated by Django 4.2.19 on 2025-03-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0003_remove_shortenedurl_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='access_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Access Count'),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='custom_alias',
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name='Custom Alias',
            ),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='original_url',
            field=models.URLField(verbose_name='Original URL'),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_code',
            field=models.CharField(
                max_length=10, unique=True, verbose_name='Shortened Code'
            ),
        ),
    ]
